### ISSUE TITLE
Setup 

### ISSUE THREAD

**Issue by JeanHuit** [GDGGhana/Website#2]
I keep getting issues in the setting up. especially the base url and others. @jeffgodwyll  @JahlomP . See if you can get it up and running. The quick start guide is in a markdown "setup_install.md"
Hope we can begin little by little. and ge tthis done.

**Comment by kobeBigs** [comment]
Noted John,

I shalt also take a look at it. Thanks for this man!

Regards,
Kobe

On Sun, Mar 22, 2015 at 6:59 PM, Jean Huit <notifications@github.com> wrote:

> I keep getting issues in the setting up. especially the base url and
> others. @jeffgodwyll <https://github.com/jeffgodwyll> @JahlomP
> <https://github.com/JahlomP> . See if you can get it up and running. The
> quick start guide is in a markdown "setup_install.md"
> Hope we can begin little by little. and ge tthis done.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/GDGGhana/Website/issues/2>.
>



-- 
"An extraordinary life is one lived in services to others"
-------------------------------------------

*Owusu Subramaniam Kwabena ( KOBE)*
*g+:* gplus.to/kobebigs
*twitter:* @kobebigs
*skype:* kobe_bigwig
*www:* http://kobebigs.com
*fone: *+233248317498 / +233265768096

**Comment by JahlomP** [comment]
Will look at it

**Comment by jeffgodwyll** [comment]
@JeanHuit OK. I'll look into it too. :+1:

**Comment by JeanHuit** [comment]
Since no one got back here, i have changed things and am closing the issue.

**Comment by JahlomP** [comment]
ok
