### ISSUE TITLE
How far with this website?

### ISSUE THREAD

**Issue by JahlomP** [GDGGhana/Website#4]
I suggest  some few willing guys with diff expertise be chosen. Two days be dedicated. so they meet at a tech hub to work on it. If they could be provided with breakfast, launch and supper it will be great.

Aside the other option is to contract some of the GDG members to build it.

**Comment by jeffgodwyll** [comment]
This just server

**Comment by jeffgodwyll** [comment]
This serves as the landing page now, per @JeanHuit's cool commit https://github.com/GDGGhana/Website/commit/349b5e639275be605040619f128bd55f15be700a
